# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VerifySeparationApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VerifySeparationApp

  target 'VerifySeparationAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift'

  end

end
